<?php

/**
 * Enregistrement local des groupes de champs ACF du thème Conservatoire.
 *
 * Hooké sur `acf/init` dans inc/actions.php. Les définitions sont la source
 * de vérité du projet — modifier dans l'admin ACF ne suffit pas, il faut
 * répercuter ici ou re-exporter le JSON et le reconvertir.
 *
 * Garde-fou : sortie silencieuse si ACF n'est pas chargé.
 *
 * @return void
 */
function crdtheme_register_acf_fields() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

    // ----- Contenu - Événement (Single)
    acf_add_local_field_group(array(
    'key' => 'group_69a591e41fdc2',
    'title' => 'Contenu - Événement (Single)',
    'fields' => array(
      array(
        'key' => 'field_69a591e4791ad',
        'label' => 'Date de début',
        'name' => 'event_date',
        'aria-label' => '',
        'type' => 'date_time_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'display_format' => 'd/m/Y G:i',
        'return_format' => 'd/m/Y G:i',
        'first_day' => 1,
        'default_to_current_date' => 0,
        'allow_in_bindings' => 0,
      ),
      array(
        'key' => 'field_69a71b5e5f2b4',
        'label' => 'Galerie photos',
        'name' => 'event_gallery',
        'aria-label' => '',
        'type' => 'gallery',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min' => '',
        'max' => '',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'insert' => 'append',
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_69a9c2a3f7b85',
        'label' => 'Programme',
        'name' => 'event_program',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Ajouter un élément au programme',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_69a9c2cef7b86',
            'label' => 'Heure / Partie',
            'name' => 'program_time',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => 'Ex : 20h30 ou Partie I',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '20',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a9c2a3f7b85',
          ),
          array(
            'key' => 'field_69a9c2e3f7b87',
            'label' => 'Titre / Œuvre',
            'name' => 'program_title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '40',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a9c2a3f7b85',
          ),
          array(
            'key' => 'field_69a9c2f3f7b88',
            'label' => 'Détail',
            'name' => 'program_detail',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => 'Ex : Compositeur, interprète, instrument',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '40',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a9c2a3f7b85',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'agenda',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
  ));

    // ----- Contenu - Page Accueil
    acf_add_local_field_group(array(
    'key' => 'group_69a71c4a52c10',
    'title' => 'Contenu - Page Accueil',
    'fields' => array(
      array(
        'key' => 'field_69a726fc23de4',
        'label' => 'Section',
        'name' => 'section',
        'aria-label' => '',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layouts' => array(
          'layout_69a727063e044' => array(
            'key' => 'layout_69a727063e044',
            'name' => 'section_numbers',
            'label' => 'Chiffres clés',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_69a7270b23de5',
                'label' => 'Chapo',
                'name' => 'numbers_subtitle',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'allow_in_bindings' => 0,
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
              ),
              array(
                'key' => 'field_69a7280e23df5',
                'label' => 'Afficher le CTA ?',
                'name' => 'numbers_show_cta',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_69a7281923df6',
                'label' => 'Texte du CTA',
                'name' => 'numbers_cta_label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_69a7280e23df5',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_69a7282223df7',
                'label' => 'Lien du CTA',
                'name' => 'numbers_cta_link',
                'aria-label' => '',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_69a7280e23df5',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'url',
                'allow_in_bindings' => 0,
              ),
              array(
                'key' => 'field_69a7282d23df8',
                'label' => 'Image',
                'name' => 'numbers_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'allow_in_bindings' => 0,
                'preview_size' => 'medium',
              ),
              array(
                'key' => 'field_69a7283723df9',
                'label' => 'Chiffres',
                'name' => 'numbers_items',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'table',
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Ajouter un chiffre',
                'rows_per_page' => 20,
                'sub_fields' => array(
                  array(
                    'key' => 'field_69a7284623dfa',
                    'label' => 'Valeur',
                    'name' => 'number_value',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'Ex : 2 500 ou 98%',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => 30,
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69a7283723df9',
                  ),
                  array(
                    'key' => 'field_69a7285023dfb',
                    'label' => 'Label',
                    'name' => 'number_label',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'Ex : élèves inscrits',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => 50,
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69a7283723df9',
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          'layout_69a7271723de6' => array(
            'key' => 'layout_69a7271723de6',
            'name' => 'section_featured',
            'label' => 'Contenu mis en avant',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_69a7279223df0',
                'label' => 'Titre',
                'name' => 'featured_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_69a732023899d',
                'label' => 'Chapo',
                'name' => 'featured_subtitle',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
              ),
              array(
                'key' => 'field_69a732b0115d3',
                'label' => 'Afficher le CTA ?',
                'name' => 'featured_show_cta',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_69a7279b23df1',
                'label' => 'Texte du CTA',
                'name' => 'featured_cta_label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_69a732b0115d3',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_69a727a923df2',
                'label' => 'Lien du CTA',
                'name' => 'featured_cta_link',
                'aria-label' => '',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_69a732b0115d3',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'url',
                'allow_in_bindings' => 0,
              ),
              array(
                'key' => 'field_69a7324f68fe8',
                'label' => 'Afficher les événements ?',
                'name' => 'featured_show_events',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          'layout_69a7271f23de8' => array(
            'key' => 'layout_69a7271f23de8',
            'name' => 'section_banner',
            'label' => 'Bannière avec image de fond',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_69a7272d23dea',
                'label' => 'Titre',
                'name' => 'banner_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_69a7273523deb',
                'label' => 'Chapo',
                'name' => 'banner_subtitle',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
              ),
              array(
                'key' => 'field_69a7274323dec',
                'label' => 'Afficher le CTA ?',
                'name' => 'banner_show_cta',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_69a7275023ded',
                'label' => 'Texte du CTA',
                'name' => 'banner_cta_label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_69a7274323dec',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_69a7275923dee',
                'label' => 'Lien du CTA',
                'name' => 'banner_cta_link',
                'aria-label' => '',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_69a7274323dec',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'url',
                'allow_in_bindings' => 0,
              ),
              array(
                'key' => 'field_69a7276723def',
                'label' => 'Image de fond',
                'name' => 'banner_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Préférez une image > 1400px de large.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'allow_in_bindings' => 0,
                'preview_size' => 'medium',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
        ),
        'min' => '',
        'max' => '',
        'button_label' => 'Ajouter une section',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page_type',
          'operator' => '==',
          'value' => 'front_page',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
  ));

    // ----- Contenu - Page Contact
    acf_add_local_field_group(array(
    'key' => 'group_69a840a00888d',
    'title' => 'Contenu - Page Contact',
    'fields' => array(
      array(
        'key' => 'field_69a840a0025d7',
        'label' => 'Horaires d\'accueil',
        'name' => 'contact_hours',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'Un horaire par ligne. Ex : Lundi – Vendredi : 9h – 19h',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Lundi – Vendredi : 9h – 19h
Samedi : 9h – 12h
Fermé les jours fériés',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'rows' => 4,
        'placeholder' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_69a8412c025d8',
        'label' => 'Texte d\'introduction (sites)',
        'name' => 'contact_locations_intro',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Le Conservatoire dispose de plusieurs sites répartis sur le territoire du Grand Belfort.',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'rows' => 2,
        'placeholder' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_69a84195025d9',
        'label' => 'Sites',
        'name' => 'contact_locations',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 1,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Ajouter un site',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_69a841b5025da',
            'label' => 'Nom du site',
            'name' => 'location_name',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a84195025d9',
          ),
          array(
            'key' => 'field_69a841df025db',
            'label' => 'Adresse complète',
            'name' => 'location_address',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a84195025d9',
          ),
          array(
            'key' => 'field_69a841f5025dc',
            'label' => 'Disciplines',
            'name' => 'location_disciplines',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => 'Ex : Musique, Danse',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a84195025d9',
          ),
        ),
      ),
      array(
        'key' => 'field_69a84408810ae',
        'label' => 'Texte d\'introduction (accès)',
        'name' => 'contact_access_intro',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'rows' => '',
        'placeholder' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_69a8442c810af',
        'label' => 'Moyens d\'accès',
        'name' => 'contact_access_items',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Ajouter un moyen d\'accès',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_69a84442810b0',
            'label' => 'Moyen',
            'name' => 'access_type',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => 'Ex : En voiture, En bus',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => 30,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a8442c810af',
          ),
          array(
            'key' => 'field_69a84457810b1',
            'label' => 'Détail',
            'name' => 'access_detail',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => 50,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a8442c810af',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-contact.php',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
  ));

    // ----- Contenu - Page Plan du site
    acf_add_local_field_group(array(
    'key' => 'group_69a9a57017e41',
    'title' => 'Contenu - Page Plan du site',
    'fields' => array(
      array(
        'key' => 'field_69a9a5705d81a',
        'label' => 'Rubriques principales',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_69a9a6abcc991',
        'label' => 'Pages principales',
        'name' => 'sitemap_main_pages',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Ajouter une page',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_69a9a58b5d81c',
            'label' => 'Titre de la page',
            'name' => 'sitemap_main_page_title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a9a6abcc991',
          ),
          array(
            'key' => 'field_69a9a5815d81b',
            'label' => 'Description de la page',
            'name' => 'sitemap_main_page_description',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a9a6abcc991',
          ),
          array(
            'key' => 'field_69a9a5bc5d81d',
            'label' => 'Lien vers la page',
            'name' => 'sitemap_main_page_link',
            'aria-label' => '',
            'type' => 'page_link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => '',
            'post_status' => '',
            'taxonomy' => '',
            'allow_archives' => 1,
            'multiple' => 0,
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'parent_repeater' => 'field_69a9a6abcc991',
          ),
        ),
      ),
      array(
        'key' => 'field_69a9a5d55d81e',
        'label' => 'Informations légales',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_69a9a67fcc990',
        'label' => 'Pages informations légales',
        'name' => 'sitemap_legal_pages',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Ajouter une page',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_69a9a5f35d821',
            'label' => 'Titre de la page',
            'name' => 'sitemap_legal_page_title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a9a67fcc990',
          ),
          array(
            'key' => 'field_69a9a5f25d820',
            'label' => 'Description de la page',
            'name' => 'sitemap_legal_page_description',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a9a67fcc990',
          ),
          array(
            'key' => 'field_69a9a5f15d81f',
            'label' => 'Lien vers la page',
            'name' => 'sitemap_legal_page_link',
            'aria-label' => '',
            'type' => 'page_link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => '',
            'post_status' => '',
            'taxonomy' => '',
            'allow_archives' => 1,
            'multiple' => 0,
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'parent_repeater' => 'field_69a9a67fcc990',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page',
          'operator' => '==',
          'value' => '247',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
  ));

    // ----- Contenu - Pages
    acf_add_local_field_group(array(
    'key' => 'group_69a719d198bd7',
    'title' => 'Contenu - Pages',
    'fields' => array(
      array(
        'key' => 'field_69b191c85b715',
        'label' => 'Carousel',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_69b187ae47659',
        'label' => 'Afficher un carousel ?',
        'name' => 'carousel_display',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_69a719d1e3774',
        'label' => 'Images du carousel',
        'name' => 'carousel_images',
        'aria-label' => '',
        'type' => 'gallery',
        'instructions' => 'Glissez-déposez les images dans l\'ordre d\'affichage souhaité.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_69b187ae47659',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min' => '',
        'max' => '',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'insert' => 'append',
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_69b191e45b716',
        'label' => 'Formulaire',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_69b187fb4765b',
        'label' => 'Ajouter un formulaire ?',
        'name' => 'form_display',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_69b1880f4765c',
        'label' => 'Shortcode du formulaire',
        'name' => 'form_shortcode',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'Copiez-collez le shortcode fourni par votre plugin de formulaire. Ex : [contact-form-7 id="123"]',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_69b187fb4765b',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '[contact-form-7 id="..."]',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_69b191ef5b717',
        'label' => 'Pages légales',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_69b188804765e',
        'label' => 'Est-ce une page légale ?',
        'name' => 'legal_page',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => 'Cochez si cette page est une page de mentions légales, CGU, politique de confidentialité, etc.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_69b1f2cf8f6f1',
        'label' => 'Fichiers à télécharger',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_69b1f33e8f6f5',
        'label' => 'Ajouter des fichiers à télécharger ?',
        'name' => 'files_display',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_69b1f2dd8f6f2',
        'label' => 'Fichiers',
        'name' => 'files',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_69b1f33e8f6f5',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Ajouter un élément',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_69b1f30b8f6f3',
            'label' => 'Intitulé',
            'name' => 'file_label',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69b1f2dd8f6f2',
          ),
          array(
            'key' => 'field_69b1f31d8f6f4',
            'label' => 'Fichier',
            'name' => 'file_upload',
            'aria-label' => '',
            'type' => 'file',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 0,
            'parent_repeater' => 'field_69b1f2dd8f6f2',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-contact.php',
        ),
      ),
      array(
        array(
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'default',
        ),
        array(
          'param' => 'page_type',
          'operator' => '!=',
          'value' => 'front_page',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
  ));

    // ----- Contenu — Page Enseignements
    acf_add_local_field_group(array(
    'key' => 'group_enseignement',
    'title' => 'Contenu — Page Enseignements',
    'fields' => array(
      array(
        'key' => 'field_tab_disciplines',
        'label' => 'Disciplines',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => false,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_ens_disciplines',
        'label' => 'Disciplines',
        'name' => 'teaching_disciplines',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'Une entrée par discipline. L\'ordre détermine l\'affichage et les liens du hero.',
        'required' => false,
        'conditional_logic' => false,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'min' => 1,
        'max' => 0,
        'layout' => 'block',
        'button_label' => '+ Ajouter une discipline',
        'rows_per_page' => 20,
        'collapsed' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_disc_titre',
            'label' => 'Titre',
            'name' => 'discipline_title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => 'Ex : Musique',
            'required' => false,
            'conditional_logic' => false,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_ens_disciplines',
          ),
          array(
            'key' => 'field_disc_intro',
            'label' => 'Texte d\'introduction',
            'name' => 'discipline_intro',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => false,
            'conditional_logic' => false,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'rows' => 3,
            'new_lines' => 'wpautop',
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'parent_repeater' => 'field_ens_disciplines',
          ),
          array(
            'key' => 'field_disc_cycles',
            'label' => 'Tableau des cycles',
            'name' => 'discipline_cycles',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => false,
            'conditional_logic' => false,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '+ Ajouter un cycle',
            'rows_per_page' => 20,
            'collapsed' => '',
            'parent_repeater' => 'field_ens_disciplines',
            'sub_fields' => array(
              array(
                'key' => 'field_cycle_nom',
                'label' => 'Cycle',
                'name' => 'cycle_name',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Ex : Initiation, 1er cycle',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                  'width' => 20,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'parent_repeater' => 'field_disc_cycles',
              ),
              array(
                'key' => 'field_cycle_age',
                'label' => 'Âge / Niveau',
                'name' => 'cycle_age_level',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Ex : 6-8 ans, Débutant',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                  'width' => 20,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'parent_repeater' => 'field_disc_cycles',
              ),
              array(
                'key' => 'field_cycle_contenu',
                'label' => 'Contenu',
                'name' => 'cycle_content',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                  'width' => 40,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'parent_repeater' => 'field_disc_cycles',
              ),
            ),
          ),
          array(
            'key' => 'field_disc_image',
            'label' => 'Image illustrative',
            'name' => 'discipline_image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => 'Optionnel — affiché sous le tableau des cycles.',
            'required' => false,
            'conditional_logic' => false,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => 0,
            'min_height' => 0,
            'min_size' => 0,
            'max_width' => 0,
            'max_height' => 0,
            'max_size' => 0,
            'mime_types' => '',
            'parent_repeater' => 'field_ens_disciplines',
          ),
          array(
            'key' => 'field_disc_image_legende',
            'label' => 'Légende de l\'image',
            'name' => 'discipline_image_caption',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => false,
            'conditional_logic' => false,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_ens_disciplines',
          ),
          array(
            'key' => 'field_disc_pratiques',
            'label' => 'Pratiques collectives',
            'name' => 'discipline_collective_practices',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => 'Laisser vide si non applicable pour cette discipline.',
            'required' => false,
            'conditional_logic' => false,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '+ Ajouter une pratique',
            'rows_per_page' => 20,
            'collapsed' => '',
            'parent_repeater' => 'field_ens_disciplines',
            'sub_fields' => array(
              array(
                'key' => 'field_pratique_nom',
                'label' => 'Nom',
                'name' => 'practice_name',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Ex : Orchestre de jeunes, Chœur',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                  'width' => 60,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'parent_repeater' => 'field_disc_pratiques',
              ),
            ),
          ),
          array(
            'key' => 'field_69a84ef736be2',
            'label' => 'Instruments enseignés',
            'name' => 'discipline_instruments',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'table',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Ajouter une famille',
            'rows_per_page' => 20,
            'parent_repeater' => 'field_ens_disciplines',
            'sub_fields' => array(
              array(
                'key' => 'field_69a84f1136be3',
                'label' => 'Famille',
                'name' => 'instrument_family',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Ex : Cordes, Vents, Percussions',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => 30,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'parent_repeater' => 'field_69a84ef736be2',
              ),
              array(
                'key' => 'field_69a84f2736be4',
                'label' => 'Instruments',
                'name' => 'instrument_list',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Séparés par des virgules. Ex : Violon, Alto, Violoncelle',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => 70,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'parent_repeater' => 'field_69a84ef736be2',
              ),
            ),
          ),
        ),
      ),
      array(
        'key' => 'field_tab_ems',
        'label' => 'EMS & CHA',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => false,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_ens_ems_titre',
        'label' => 'Titre EMS',
        'name' => 'teaching_ems_title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => false,
        'conditional_logic' => false,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Enseignement musical scolaire (EMS)',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_ens_ems_texte',
        'label' => 'Texte EMS',
        'name' => 'teaching_ems_content',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'Laisser vide pour masquer ce bloc.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_ens_cha_titre',
        'label' => 'Titre CHA',
        'name' => 'teaching_cha_title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => false,
        'conditional_logic' => false,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Classes à horaires aménagés (CHA)',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_ens_cha_texte',
        'label' => 'Texte CHA',
        'name' => 'teaching_cha_content',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'Laisser vide pour masquer ce bloc.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_tab_fichiers',
        'label' => 'Fichiers à télécharger',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => false,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_ens_fichiers',
        'label' => 'Fichiers',
        'name' => 'teaching_files',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'PDF, Word, etc. Chaque fichier ajoute une ligne téléchargeable.',
        'required' => false,
        'conditional_logic' => false,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => '+ Ajouter un fichier',
        'rows_per_page' => 20,
        'collapsed' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_fichier_label',
            'label' => 'Intitulé',
            'name' => 'file_label',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => 'Ex : Brochure 2024-2025',
            'required' => false,
            'conditional_logic' => false,
            'wrapper' => array(
              'width' => 50,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_ens_fichiers',
          ),
          array(
            'key' => 'field_fichier_file',
            'label' => 'Fichier',
            'name' => 'file_upload',
            'aria-label' => '',
            'type' => 'file',
            'instructions' => '',
            'required' => false,
            'conditional_logic' => false,
            'wrapper' => array(
              'width' => 50,
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => 0,
            'max_size' => 0,
            'mime_types' => '',
            'parent_repeater' => 'field_ens_fichiers',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-enseignements.php',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
  ));

    // ----- Informations générales
    acf_add_local_field_group(array(
    'key' => 'group_69a6e87a6295d',
    'title' => 'Informations générales',
    'fields' => array(
      array(
        'key' => 'field_69a6e87a6ff10',
        'label' => 'Adresse principale',
        'name' => 'site_address',
        'aria-label' => '',
        'type' => 'google_map',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'center_lat' => '',
        'center_lng' => '',
        'zoom' => '',
        'height' => '',
        'allow_in_bindings' => 0,
      ),
      array(
        'key' => 'field_69a6e8896ff11',
        'label' => 'Email',
        'name' => 'site_email',
        'aria-label' => '',
        'type' => 'email',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_69a6e8e86ff13',
        'label' => 'Téléphone',
        'name' => 'site_phone',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_69a6e8d76ff12',
        'label' => 'Logo (footer)',
        'name' => 'site_logo_footer',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'Logo affiché dans le pied de page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'allow_in_bindings' => 0,
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_69a6e9206ff14',
        'label' => 'Logo Grand Belfort',
        'name' => 'site_logo_partner',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'Logo du partenaire institutionnel.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'allow_in_bindings' => 0,
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_69a6f2a4e9ff3',
        'label' => 'Réseaux sociaux',
        'name' => 'site_social_networks',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Ajouter un réseau social',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_6a02f5c08d6aa',
            'label' => 'Icône',
            'name' => 'social_network_icon',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 0,
            'preview_size' => 'medium',
            'parent_repeater' => 'field_69a6f2a4e9ff3',
          ),
          array(
            'key' => 'field_69a6f2bee9ff4',
            'label' => 'Nom',
            'name' => 'social_network_name',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => 'Optionnel. Remplace le nom de la plateforme.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '25',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a6f2a4e9ff3',
          ),
          array(
            'key' => 'field_69a6f2d5e9ff5',
            'label' => 'URL',
            'name' => 'social_network_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => 50,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'allow_in_bindings' => 0,
            'placeholder' => 'https://...',
            'parent_repeater' => 'field_69a6f2a4e9ff3',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'infos-site',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
  ));

    // ----- Option - Menu Enseignements
    acf_add_local_field_group(array(
    'key' => 'group_69a72408496e3',
    'title' => 'Option - Menu Enseignements',
    'fields' => array(
      array(
        'key' => 'field_69a724080266f',
        'label' => 'Éléments du menu',
        'name' => 'menu_items',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Ajouter un élément',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_69a7246a02670',
            'label' => 'Icône / Image',
            'name' => 'menu_item_icon',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => 'SVG ou PNG, fond transparent recommandé.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => 20,
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 0,
            'preview_size' => 'thumbnail',
            'parent_repeater' => 'field_69a724080266f',
          ),
          array(
            'key' => 'field_69a7247802671',
            'label' => 'Texte',
            'name' => 'menu_item_label',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => 40,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_69a724080266f',
          ),
          array(
            'key' => 'field_69a7248902672',
            'label' => 'Lien',
            'name' => 'menu_item_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => 40,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'allow_in_bindings' => 0,
            'placeholder' => 'https://...',
            'parent_repeater' => 'field_69a724080266f',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-enseignements',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
  ));

    // ----- Options - En-têtes
    acf_add_local_field_group(array(
    'key' => 'group_69a6f5b0914c0',
    'title' => 'Options - En-têtes',
    'fields' => array(
      array(
        'key' => 'field_69a73a074cb8f',
        'label' => 'En-tête — Archive Agenda',
        'name' => 'header_archive_agenda',
        'aria-label' => '',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_69a73a284cb90',
            'label' => 'Image',
            'name' => 'img_header_archive',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'id',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 0,
            'preview_size' => 'medium',
          ),
          array(
            'key' => 'field_69a73a3e4cb91',
            'label' => 'Description',
            'name' => 'desc_header_archive',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'rows' => '',
            'placeholder' => '',
            'new_lines' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_69a73b607a9f8',
        'label' => 'En-tête par défaut',
        'name' => 'header_default',
        'aria-label' => '',
        'type' => 'group',
        'instructions' => 'Utilisé sur toutes les pages sans image d\'en-tête spécifique.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_69a73b767a9f9',
            'label' => 'Image',
            'name' => 'img_header_default',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'id',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 0,
            'preview_size' => 'medium',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-en-tetes-archives',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
  ));

}
